//  SigTable.swift
//  Fieldwatch
//
//  Generated from the original DeviceExplain.signatureHints catalog.
//  (exact, key, bucket, label, weight) � first match wins.

import Foundation

struct SigRule {
    let contains: Bool
    let key: String
    let bucket: String
    let label: String
    let weight: Int
}

let SigRules: [SigRule] = [
        SigRule(contains: false, key: "tesla", bucket: "vehicle", label: "a Tesla vehicle (including Cybertruck) or phone-as-key", weight: 7),
        SigRule(contains: false, key: "google", bucket: "phone", label: "a Pixel or other Google radio", weight: 6),
        SigRule(contains: false, key: "sony", bucket: "audio-personal", label: "Sony headphones, a TV, or a camera", weight: 6),
        SigRule(contains: false, key: "bose", bucket: "audio-personal", label: "Bose headphones or a speaker", weight: 7),
        SigRule(contains: false, key: "garmin", bucket: "watch", label: "a Garmin watch or inReach", weight: 7),
        SigRule(contains: false, key: "amazon", bucket: "speaker", label: "an Echo, Fire, or other Amazon radio", weight: 6),
        SigRule(contains: false, key: "fitbit", bucket: "watch", label: "a Fitbit", weight: 7),
        SigRule(contains: false, key: "oura", bucket: "wearable", label: "an Oura ring", weight: 7),
        SigRule(contains: false, key: "logitech", bucket: "hid", label: "a Logitech mouse, keyboard, or webcam", weight: 6),
        SigRule(contains: true, key: "jbl", bucket: "audio-personal", label: "JBL or Harman audio", weight: 6),
        SigRule(contains: false, key: "harman", bucket: "audio-personal", label: "JBL or Harman audio", weight: 6),
        SigRule(contains: false, key: "sonos", bucket: "audio-speaker", label: "a Sonos speaker", weight: 7),
        SigRule(contains: false, key: "gopro", bucket: "camera", label: "a GoPro", weight: 7),
        SigRule(contains: false, key: "osmo", bucket: "camera", label: "a DJI Osmo action camera", weight: 7),
        SigRule(contains: false, key: "insta360", bucket: "camera", label: "an Insta360 camera", weight: 7),
        SigRule(contains: false, key: "dji", bucket: "drone", label: "a DJI drone or controller", weight: 7),
        SigRule(contains: false, key: "remote id", bucket: "drone", label: "a drone broadcasting ASTM Remote ID", weight: 8),
        SigRule(contains: false, key: "skydio", bucket: "drone", label: "a Skydio drone", weight: 7),
        SigRule(contains: false, key: "autel", bucket: "drone", label: "an Autel drone", weight: 7),
        SigRule(contains: false, key: "parrot", bucket: "drone", label: "a Parrot ANAFI or Bebop drone", weight: 7),
        SigRule(contains: false, key: "hoverair", bucket: "drone", label: "a HOVERAir flying camera", weight: 7),
        SigRule(contains: false, key: "netgear", bucket: "ap", label: "a NETGEAR or Orbi access point", weight: 6),
        SigRule(contains: false, key: "orbi", bucket: "ap", label: "a NETGEAR or Orbi access point", weight: 6),
        SigRule(contains: false, key: "tp-link", bucket: "ap", label: "a TP-Link access point", weight: 6),
        SigRule(contains: false, key: "asus", bucket: "ap", label: "an ASUS access point", weight: 6),
        SigRule(contains: false, key: "linksys", bucket: "ap", label: "a Linksys or Velop access point", weight: 6),
        SigRule(contains: false, key: "eero", bucket: "ap", label: "an Eero mesh node", weight: 6),
        SigRule(contains: false, key: "google wifi", bucket: "ap", label: "a Google Wifi or Nest Wifi point", weight: 6),
        SigRule(contains: false, key: "d-link", bucket: "ap", label: "a D-Link access point", weight: 6),
        SigRule(contains: false, key: "belkin", bucket: "ap", label: "a Belkin access point", weight: 6),
        SigRule(contains: false, key: "xfinity", bucket: "ap", label: "an Xfinity gateway or hotspot", weight: 6),
        SigRule(contains: false, key: "spectrum", bucket: "ap", label: "a Spectrum gateway or Spectrum Mobile hotspot", weight: 6),
        SigRule(contains: false, key: "at&t", bucket: "ap", label: "an AT&T gateway or attwifi hotspot", weight: 6),
        SigRule(contains: false, key: "verizon", bucket: "ap", label: "a Verizon or Fios gateway", weight: 6),
        SigRule(contains: false, key: "starlink", bucket: "ap", label: "a Starlink router", weight: 7),
        SigRule(contains: false, key: "meraki", bucket: "ap", label: "a Cisco Meraki access point", weight: 7),
        SigRule(contains: false, key: "cisco", bucket: "ap", label: "a Cisco Aironet, Catalyst, Business, RV, or SPVTG access point", weight: 7),
        SigRule(contains: false, key: "mist", bucket: "ap", label: "a Juniper Mist access point", weight: 7),
        SigRule(contains: false, key: "t-mobile", bucket: "ap", label: "a T-Mobile Home Internet gateway or hotspot", weight: 6),
        SigRule(contains: false, key: "humax", bucket: "ap", label: "a HUMAX gateway (often T-Mobile Home Internet)", weight: 6),
        SigRule(contains: false, key: "sagemcom", bucket: "ap", label: "a Sagemcom ISP gateway", weight: 6),
        SigRule(contains: false, key: "arcadyan", bucket: "ap", label: "an Arcadyan ISP gateway", weight: 6),
        SigRule(contains: false, key: "askey", bucket: "ap", label: "an Askey ISP / 5G gateway", weight: 6),
        SigRule(contains: false, key: "calix", bucket: "ap", label: "a Calix fiber gateway", weight: 6),
        SigRule(contains: false, key: "nokia", bucket: "ap", label: "a Nokia Solutions and Networks gateway", weight: 6),
        SigRule(contains: false, key: "airties", bucket: "ap", label: "an AirTies ISP mesh node", weight: 6),
        SigRule(contains: false, key: "tenda", bucket: "ap", label: "a Tenda access point", weight: 6),
        SigRule(contains: false, key: "ruijie", bucket: "ap", label: "a Ruijie or Reyee access point", weight: 6),
        SigRule(contains: false, key: "dwnet", bucket: "ap", label: "a DWnet access point", weight: 6),
        SigRule(contains: false, key: "wavlink", bucket: "ap", label: "a WAVLINK access point", weight: 6),
        SigRule(contains: false, key: "sercomm", bucket: "ap", label: "a Sercomm ISP gateway", weight: 6),
        SigRule(contains: false, key: "luxul", bucket: "ap", label: "a Luxul access point", weight: 6),
        SigRule(contains: false, key: "sophos", bucket: "ap", label: "a Sophos firewall or access point", weight: 7),
        SigRule(contains: false, key: "aumovio", bucket: "hotspot", label: "an AUMOVIO / Continental vehicle Wi-Fi radio", weight: 6),
        SigRule(contains: false, key: "centurylink", bucket: "ap", label: "a CenturyLink gateway", weight: 6),
        SigRule(contains: false, key: "gm hotspot", bucket: "hotspot", label: "a GM in-car hotspot (Cadillac / GMC / Buick / Chevrolet)", weight: 6),
        SigRule(contains: false, key: "audi mmi", bucket: "hotspot", label: "an Audi MMI in-car hotspot", weight: 6),
        SigRule(contains: false, key: "extreme", bucket: "ap", label: "an Extreme Networks access point", weight: 7),
        SigRule(contains: false, key: "adtran", bucket: "ap", label: "an Adtran fiber gateway (often CenturyLink / Quantum Fiber OEM)", weight: 6),
        SigRule(contains: false, key: "cambium", bucket: "ap", label: "a Cambium or IgniteNet access point", weight: 6),
        SigRule(contains: false, key: "trendnet", bucket: "ap", label: "a TRENDnet access point", weight: 6),
        SigRule(contains: false, key: "cudy", bucket: "ap", label: "a Cudy travel or home router", weight: 6),
        SigRule(contains: false, key: "snapav", bucket: "ap", label: "a SnapAV / Control4 / Wattbox access point", weight: 6),
        SigRule(contains: false, key: "arlo", bucket: "camera", label: "an Arlo camera or VMB base station", weight: 6),
        SigRule(contains: false, key: "vantiva", bucket: "ap", label: "a Vantiva or Technicolor ISP gateway", weight: 6),
        SigRule(contains: false, key: "hitron", bucket: "ap", label: "a Hitron cable gateway (often Xfinity OEM)", weight: 6),
        SigRule(contains: false, key: "actiontec", bucket: "ap", label: "an Actiontec FiOS or Frontier gateway", weight: 6),
        SigRule(contains: false, key: "buffalo", bucket: "ap", label: "a Buffalo AirStation or router", weight: 6),
        SigRule(contains: false, key: "grandstream", bucket: "ap", label: "a Grandstream GWN access point", weight: 6),
        SigRule(contains: false, key: "edgecore", bucket: "ap", label: "an Edgecore access point", weight: 7),
        SigRule(contains: false, key: "watchguard ap", bucket: "ap", label: "a WatchGuard firewall or access point", weight: 7),
        SigRule(contains: false, key: "mojo", bucket: "ap", label: "a Mojo Networks / Arista Cognitive Wi-Fi access point", weight: 7),
        SigRule(contains: false, key: "winegard", bucket: "hotspot", label: "a Winegard RV or marine Wi-Fi radio", weight: 6),
        SigRule(contains: false, key: "inseego", bucket: "ap", label: "an Inseego 5G or MiFi hotspot", weight: 6),
        SigRule(contains: false, key: "franklin", bucket: "ap", label: "a Franklin Technology 5G home-internet gateway (RG3100 class)", weight: 6),
        SigRule(contains: false, key: "synology", bucket: "ap", label: "a Synology NAS or router access point", weight: 6),
        SigRule(contains: false, key: "aruba", bucket: "ap", label: "an HPE Aruba Instant or Instant On access point", weight: 7),
        SigRule(contains: false, key: "ruckus", bucket: "ap", label: "a RUCKUS access point", weight: 7),
        SigRule(contains: false, key: "fortinet", bucket: "ap", label: "a Fortinet FortiAP or FortiWiFi", weight: 7),
        SigRule(contains: false, key: "mikrotik", bucket: "ap", label: "a MikroTik router or access point", weight: 6),
        SigRule(contains: false, key: "engenius", bucket: "ap", label: "an EnGenius access point", weight: 6),
        SigRule(contains: false, key: "zyxel", bucket: "ap", label: "a Zyxel gateway or access point", weight: 6),
        SigRule(contains: false, key: "peplink", bucket: "ap", label: "a Peplink or Pepwave router", weight: 6),
        SigRule(contains: false, key: "openwrt", bucket: "ap", label: "an OpenWrt router", weight: 6),
        SigRule(contains: false, key: "arris", bucket: "ap", label: "an Arris or SURFboard cable gateway", weight: 6),
        SigRule(contains: false, key: "unifi ap", bucket: "ap", label: "a Ubiquiti UniFi access point", weight: 7),
        SigRule(contains: false, key: "unifi protect", bucket: "camera", label: "a UniFi Protect Instant camera", weight: 7),
        SigRule(contains: false, key: "unifi", bucket: "ap", label: "a UniFi / Ubiquiti name", weight: 5),
        SigRule(contains: false, key: "ecobee", bucket: "thermostat", label: "an ecobee thermostat", weight: 7),
        SigRule(contains: false, key: "sensi", bucket: "thermostat", label: "a Sensi thermostat", weight: 6),
        SigRule(contains: false, key: "honeywell home", bucket: "thermostat", label: "a Honeywell Home or Lyric thermostat", weight: 6),
        SigRule(contains: true, key: "honeywell xenon", bucket: "health", label: "a Honeywell Xenon healthcare barcode scanner", weight: 7),
        SigRule(contains: false, key: "omron", bucket: "health", label: "an Omron blood-pressure cuff or scale", weight: 7),
        SigRule(contains: false, key: "withings", bucket: "health", label: "a Withings scale or blood-pressure monitor", weight: 7),
        SigRule(contains: false, key: "dexcom", bucket: "health", label: "a Dexcom glucose sensor", weight: 7),
        SigRule(contains: false, key: "nest thermostat", bucket: "thermostat", label: "a Nest thermostat or Nest Labs BLE sensor", weight: 6),
        SigRule(contains: false, key: "nest weave", bucket: "sensor", label: "a Nest Protect, camera, or other Weave BLE device", weight: 7),
        SigRule(contains: false, key: "haiku fan", bucket: "fan", label: "a Haiku or Mammoth ceiling fan", weight: 7),
        SigRule(contains: false, key: "haiku", bucket: "fan", label: "a Haiku or Mammoth ceiling fan", weight: 7),
        SigRule(contains: false, key: "tuya", bucket: "iot", label: "a Tuya BLE gadget (plug, light, camera, sensor)", weight: 6),
        SigRule(contains: false, key: "seos", bucket: "access", label: "an ASSA ABLOY lock, Yale lock, HID reader, or Seos credential", weight: 7),
        SigRule(contains: false, key: "assa abloy", bucket: "access", label: "an ASSA ABLOY lock, Yale lock, HID reader, or Seos credential", weight: 7),
        SigRule(contains: false, key: "august", bucket: "lock", label: "an August smart lock", weight: 7),
        SigRule(contains: false, key: "schlage", bucket: "lock", label: "a Schlage or Allegion lock", weight: 7),
        SigRule(contains: false, key: "nuki", bucket: "lock", label: "a Nuki lock or opener", weight: 7),
        SigRule(contains: false, key: "salto", bucket: "access", label: "a SALTO access reader or lock", weight: 7),
        SigRule(contains: false, key: "dormakaba", bucket: "access", label: "a dormakaba, Saflok, or Oracode lock", weight: 7),
        SigRule(contains: false, key: "lockly", bucket: "lock", label: "a Lockly smart lock", weight: 6),
        SigRule(contains: false, key: "kevo", bucket: "lock", label: "a Kwikset Kevo or Unikey lock", weight: 7),
        SigRule(contains: false, key: "master lock", bucket: "lock", label: "a Master Lock padlock", weight: 7),
        SigRule(contains: false, key: "igloohome", bucket: "lock", label: "an igloohome lock or keybox", weight: 7),
        SigRule(contains: false, key: "tedee", bucket: "lock", label: "a Tedee smart lock", weight: 7),
        SigRule(contains: false, key: "paxton", bucket: "access", label: "a Paxton reader or Net2 access point", weight: 7),
        SigRule(contains: false, key: "kwikset", bucket: "lock", label: "a Kwikset lock", weight: 6),
        SigRule(contains: false, key: "myq", bucket: "garage", label: "a Chamberlain myQ garage hub", weight: 7),
        SigRule(contains: false, key: "chevrolet hotspot", bucket: "hotspot", label: "a Chevrolet in-car Wi-Fi hotspot", weight: 7),
        SigRule(contains: false, key: "rivian", bucket: "vehicle", label: "a Rivian vehicle, phone key, or sensor", weight: 7),
        SigRule(contains: false, key: "ford", bucket: "vehicle", label: "a Ford or Lincoln vehicle or phone-as-key", weight: 7),
        SigRule(contains: false, key: "honda", bucket: "vehicle", label: "a Honda or Acura vehicle or phone-as-key", weight: 7),
        SigRule(contains: false, key: "hyundai", bucket: "vehicle", label: "a Hyundai or Genesis vehicle or phone-as-key", weight: 7),
        SigRule(contains: false, key: "toyota", bucket: "vehicle", label: "a Toyota or Lexus vehicle or phone-as-key", weight: 7),
        SigRule(contains: false, key: "nissan", bucket: "vehicle", label: "a Nissan or Infiniti vehicle or phone-as-key", weight: 7),
        SigRule(contains: false, key: "subaru", bucket: "vehicle", label: "a Subaru vehicle or phone-as-key", weight: 7),
        SigRule(contains: false, key: "bmw", bucket: "vehicle", label: "a BMW vehicle, phone-as-key, or factory hotspot", weight: 7),
        SigRule(contains: false, key: "volkswagen", bucket: "vehicle", label: "a Volkswagen vehicle or phone-as-key", weight: 7),
        SigRule(contains: false, key: "porsche", bucket: "vehicle", label: "a Porsche vehicle or phone-as-key", weight: 7),
        SigRule(contains: false, key: "jaguar land rover", bucket: "vehicle", label: "a Jaguar, Land Rover, or Range Rover", weight: 7),
        SigRule(contains: false, key: "byd", bucket: "vehicle", label: "a BYD vehicle or phone-as-key", weight: 7),
        SigRule(contains: false, key: "govee", bucket: "light", label: "a Govee light or sensor", weight: 6),
        SigRule(contains: false, key: "hp", bucket: "printer", label: "an HP printer", weight: 6),
        SigRule(contains: false, key: "epson", bucket: "printer", label: "an Epson EcoTank or WorkForce printer", weight: 6),
        SigRule(contains: false, key: "lg webos tv", bucket: "tv", label: "an LG webOS TV", weight: 7),
        SigRule(contains: false, key: "roku", bucket: "tv", label: "a Roku streaming stick or Roku TV (often a hidden Wi-Fi Direct remote AP)", weight: 7),
        SigRule(contains: false, key: "samsung appliance", bucket: "iot", label: "a Samsung fridge, range, oven, or cooktop (setup AP)", weight: 6),
        SigRule(contains: false, key: "ecowater", bucket: "iot", label: "an EcoWater water softener (setup AP)", weight: 6),
        SigRule(contains: false, key: "nespresso", bucket: "iot", label: "a Nespresso coffee machine", weight: 7),
        SigRule(contains: false, key: "radiacode", bucket: "sensor", label: "a RadiaCode radiation detector", weight: 7),
        SigRule(contains: false, key: "shokz", bucket: "audio-personal", label: "Shokz OpenRun or OpenFit headphones", weight: 7),
        SigRule(contains: false, key: "mercedes mbux", bucket: "hotspot", label: "a Mercedes MBUX in-car hotspot", weight: 7),
        SigRule(contains: false, key: "motive", bucket: "hotspot", label: "a Motive / KeepTruckin fleet ELD hotspot", weight: 6),
        SigRule(contains: false, key: "peoplenet", bucket: "hotspot", label: "a PeopleNet fleet ELD hotspot", weight: 6),
        SigRule(contains: false, key: "uconnect", bucket: "hotspot", label: "a Uconnect in-car hotspot", weight: 6),
        SigRule(contains: false, key: "carplay", bucket: "hotspot", label: "a CarPlay in-car hotspot", weight: 6),
        SigRule(contains: false, key: "cradlepoint", bucket: "hotspot", label: "a Cradlepoint vehicle router (often public-safety / fleet)", weight: 7),
        SigRule(contains: false, key: "airlink", bucket: "hotspot", label: "a Sierra Wireless AirLink vehicle gateway", weight: 7),
        SigRule(contains: false, key: "compex", bucket: "hotspot", label: "a Compex access point (sometimes public-safety / fleet)", weight: 6),
        SigRule(contains: false, key: "novatel wireless", bucket: "hotspot", label: "a Novatel Wireless / Inseego vehicle radio", weight: 6),
        SigRule(contains: false, key: "utility inc", bucket: "hotspot", label: "a Utility, Inc vehicle or public-safety radio", weight: 6),
        SigRule(contains: true, key: "gl.inet", bucket: "ap", label: "a GL.iNet travel router", weight: 6),
        SigRule(contains: false, key: "glinet", bucket: "ap", label: "a GL.iNet travel router", weight: 6),
        SigRule(contains: true, key: "smarttag", bucket: "tag", label: "a Samsung SmartTag", weight: 8),
        SigRule(contains: true, key: "tile", bucket: "tag", label: "a Tile tracker", weight: 8),
        SigRule(contains: false, key: "ibeacon", bucket: "beacon", label: "an iBeacon", weight: 7),
        SigRule(contains: true, key: "target atrius", bucket: "beacon", label: "a Target Atrius basket tag", weight: 8),
        SigRule(contains: false, key: "minew", bucket: "beacon", label: "a Minew BLE beacon or sensor", weight: 7),
        SigRule(contains: false, key: "estimote", bucket: "beacon", label: "an Estimote beacon", weight: 7),
        SigRule(contains: false, key: "kontakt.io", bucket: "beacon", label: "a Kontakt.io beacon", weight: 7),
        SigRule(contains: false, key: "kontakt", bucket: "beacon", label: "a Kontakt.io beacon", weight: 7),
        SigRule(contains: true, key: "bluetoad", bucket: "roadside", label: "an Iteris BlueTOAD / Vantage Velocity roadside Bluetooth travel-time reader", weight: 7),
        SigRule(contains: true, key: "bliptrack", bucket: "roadside", label: "a BLIP Systems BlipTrack roadside travel-time sensor", weight: 7),
        SigRule(contains: true, key: "raven", bucket: "acoustic", label: "a Flock Raven or ShotSpotter acoustic gunshot sensor", weight: 8),
        SigRule(contains: true, key: "shotspotter", bucket: "acoustic", label: "a Flock Raven or ShotSpotter acoustic gunshot sensor", weight: 8),
        SigRule(contains: true, key: "soundthinking", bucket: "acoustic", label: "a Flock Raven or ShotSpotter acoustic gunshot sensor", weight: 8),
        SigRule(contains: true, key: "digital ally", bucket: "camera", label: "a Digital Ally body-worn or in-car camera", weight: 8),
        SigRule(contains: true, key: "reveal media", bucket: "camera", label: "a Reveal Media body-worn camera", weight: 8),
        SigRule(contains: true, key: "bodyworn", bucket: "camera", label: "a Reveal Media body-worn camera", weight: 8),
        SigRule(contains: false, key: "wolfcom", bucket: "camera", label: "a Wolfcom body-worn or in-car camera", weight: 8),
        SigRule(contains: true, key: "i-pro", bucket: "camera", label: "a Panasonic i-PRO camera or Arbitrator in-car system", weight: 8),
        SigRule(contains: true, key: "arbitrator", bucket: "camera", label: "a Panasonic i-PRO camera or Arbitrator in-car system", weight: 8),
        SigRule(contains: true, key: "limitless", bucket: "wearable", label: "a Limitless Pendant conversation recorder", weight: 8),
        SigRule(contains: false, key: "bee pendant", bucket: "wearable", label: "a Bee Pioneer wearable recorder", weight: 8),
        SigRule(contains: true, key: "bee pioneer", bucket: "wearable", label: "a Bee Pioneer wearable recorder", weight: 8),
        SigRule(contains: false, key: "omi", bucket: "wearable", label: "an Omi pendant or OpenGlass camera glasses", weight: 8),
        SigRule(contains: true, key: "openglass", bucket: "wearable", label: "an Omi pendant or OpenGlass camera glasses", weight: 8),
        SigRule(contains: true, key: "friend pendant", bucket: "wearable", label: "a Friend Pendant necklace", weight: 8),
        SigRule(contains: true, key: "brilliant frame", bucket: "glasses", label: "Brilliant Labs Frame AR glasses", weight: 8),
        SigRule(contains: false, key: "even g1", bucket: "glasses", label: "Even Realities G1 glasses", weight: 8),
        SigRule(contains: true, key: "hayden", bucket: "camera", label: "a Hayden AI bus- or vehicle-mounted camera", weight: 8),
        SigRule(contains: true, key: "miovision", bucket: "camera", label: "a Miovision intersection traffic camera", weight: 8),
        SigRule(contains: false, key: "tattile", bucket: "camera", label: "a Tattile plate reader", weight: 8),
        SigRule(contains: true, key: "lvt", bucket: "camera", label: "an LVT / LiveView solar surveillance trailer", weight: 8),
        SigRule(contains: true, key: "liveview", bucket: "camera", label: "an LVT / LiveView solar surveillance trailer", weight: 8),
        SigRule(contains: true, key: "hanwha", bucket: "camera", label: "a Hanwha Vision / Wisenet camera", weight: 7),
        SigRule(contains: true, key: "wisenet", bucket: "camera", label: "a Hanwha Vision / Wisenet camera", weight: 7),
        SigRule(contains: false, key: "uniview", bucket: "camera", label: "a Uniview / UNV camera", weight: 7),
        SigRule(contains: false, key: "rhombus", bucket: "camera", label: "a Rhombus cloud camera", weight: 7),
        SigRule(contains: false, key: "meshcore", bucket: "mesh", label: "a MeshCore LoRa companion radio", weight: 7),
        SigRule(contains: true, key: "gotenna", bucket: "mesh", label: "a goTenna Mesh or Pro radio", weight: 7),
        SigRule(contains: false, key: "sensecap", bucket: "mesh", label: "a SenseCAP LoRaWAN / Helium gateway", weight: 7),
        SigRule(contains: true, key: "wisgate", bucket: "mesh", label: "a RAK WisGate LoRaWAN gateway", weight: 7),
        SigRule(contains: false, key: "rak wisgate", bucket: "mesh", label: "a RAK WisGate LoRaWAN gateway", weight: 7),
        SigRule(contains: false, key: "ghostesp", bucket: "pentest", label: "a GhostESP ESP32 audit board", weight: 7),
        SigRule(contains: false, key: "bruce", bucket: "pentest", label: "a Bruce ESP32 pentest board", weight: 7),
        SigRule(contains: false, key: "liteon camera radio", bucket: "module", label: "a camera-module radio (LiteOn or similar)", weight: 3),
        SigRule(contains: true, key: "chipolo", bucket: "tag", label: "a finder tag", weight: 7),
        SigRule(contains: true, key: "pebblebee", bucket: "tag", label: "a finder tag", weight: 7),
        SigRule(contains: true, key: "moto tag", bucket: "tag", label: "a finder tag", weight: 7),
        SigRule(contains: true, key: "airpods", bucket: "audio-personal", label: "AirPods", weight: 8),
]
