//  SigTable.swift
//  Fieldwatch
//
//  Generated from the original DeviceExplain.signatureHints catalog.
//  (exact, key, bucket, label, weight) — first match wins.

import Foundation

struct SigRule {
    let contains: Bool
    let key: String
    let bucket: String
    let label: String
    let weight: Int
}

let SigRules: [SigRule] = [        (false, "tesla", "vehicle", "a Tesla vehicle (including Cybertruck) or phone-as-key", 7),
        (false, "google", "phone", "a Pixel or other Google radio", 6),
        (false, "sony", "audio-personal", "Sony headphones, a TV, or a camera", 6),
        (false, "bose", "audio-personal", "Bose headphones or a speaker", 7),
        (false, "garmin", "watch", "a Garmin watch or inReach", 7),
        (false, "amazon", "speaker", "an Echo, Fire, or other Amazon radio", 6),
        (false, "fitbit", "watch", "a Fitbit", 7),
        (false, "oura", "wearable", "an Oura ring", 7),
        (false, "logitech", "hid", "a Logitech mouse, keyboard, or webcam", 6),
        (true, "jbl", "audio-personal", "JBL or Harman audio", 6),
        (false, "harman", "audio-personal", "JBL or Harman audio", 6),
        (false, "sonos", "audio-speaker", "a Sonos speaker", 7),
        (false, "gopro", "camera", "a GoPro", 7),
        (false, "osmo", "camera", "a DJI Osmo action camera", 7),
        (false, "insta360", "camera", "an Insta360 camera", 7),
        (false, "dji", "drone", "a DJI drone or controller", 7),
        (false, "remote id", "drone", "a drone broadcasting ASTM Remote ID", 8),
        (false, "skydio", "drone", "a Skydio drone", 7),
        (false, "autel", "drone", "an Autel drone", 7),
        (false, "parrot", "drone", "a Parrot ANAFI or Bebop drone", 7),
        (false, "hoverair", "drone", "a HOVERAir flying camera", 7),
        (false, "netgear", "ap", "a NETGEAR or Orbi access point", 6),
        (false, "orbi", "ap", "a NETGEAR or Orbi access point", 6),
        (false, "tp-link", "ap", "a TP-Link access point", 6),
        (false, "asus", "ap", "an ASUS access point", 6),
        (false, "linksys", "ap", "a Linksys or Velop access point", 6),
        (false, "eero", "ap", "an Eero mesh node", 6),
        (false, "google wifi", "ap", "a Google Wifi or Nest Wifi point", 6),
        (false, "d-link", "ap", "a D-Link access point", 6),
        (false, "belkin", "ap", "a Belkin access point", 6),
        (false, "xfinity", "ap", "an Xfinity gateway or hotspot", 6),
        (false, "spectrum", "ap", "a Spectrum gateway or Spectrum Mobile hotspot", 6),
        (false, "at&t", "ap", "an AT&T gateway or attwifi hotspot", 6),
        (false, "verizon", "ap", "a Verizon or Fios gateway", 6),
        (false, "starlink", "ap", "a Starlink router", 7),
        (false, "meraki", "ap", "a Cisco Meraki access point", 7),
        (false, "cisco", "ap", "a Cisco Aironet, Catalyst, Business, RV, or SPVTG access point", 7),
        (false, "mist", "ap", "a Juniper Mist access point", 7),
        (false, "t-mobile", "ap", "a T-Mobile Home Internet gateway or hotspot", 6),
        (false, "humax", "ap", "a HUMAX gateway (often T-Mobile Home Internet)", 6),
        (false, "sagemcom", "ap", "a Sagemcom ISP gateway", 6),
        (false, "arcadyan", "ap", "an Arcadyan ISP gateway", 6),
        (false, "askey", "ap", "an Askey ISP / 5G gateway", 6),
        (false, "calix", "ap", "a Calix fiber gateway", 6),
        (false, "nokia", "ap", "a Nokia Solutions and Networks gateway", 6),
        (false, "airties", "ap", "an AirTies ISP mesh node", 6),
        (false, "tenda", "ap", "a Tenda access point", 6),
        (false, "ruijie", "ap", "a Ruijie or Reyee access point", 6),
        (false, "dwnet", "ap", "a DWnet access point", 6),
        (false, "wavlink", "ap", "a WAVLINK access point", 6),
        (false, "sercomm", "ap", "a Sercomm ISP gateway", 6),
        (false, "luxul", "ap", "a Luxul access point", 6),
        (false, "sophos", "ap", "a Sophos firewall or access point", 7),
        (false, "aumovio", "hotspot", "an AUMOVIO / Continental vehicle Wi-Fi radio", 6),
        (false, "centurylink", "ap", "a CenturyLink gateway", 6),
        (false, "gm hotspot", "hotspot", "a GM in-car hotspot (Cadillac / GMC / Buick / Chevrolet)", 6),
        (false, "audi mmi", "hotspot", "an Audi MMI in-car hotspot", 6),
        (false, "extreme", "ap", "an Extreme Networks access point", 7),
        (false, "adtran", "ap", "an Adtran fiber gateway (often CenturyLink / Quantum Fiber OEM)", 6),
        (false, "cambium", "ap", "a Cambium or IgniteNet access point", 6),
        (false, "trendnet", "ap", "a TRENDnet access point", 6),
        (false, "cudy", "ap", "a Cudy travel or home router", 6),
        (false, "snapav", "ap", "a SnapAV / Control4 / Wattbox access point", 6),
        (false, "arlo", "camera", "an Arlo camera or VMB base station", 6),
        (false, "vantiva", "ap", "a Vantiva or Technicolor ISP gateway", 6),
        (false, "hitron", "ap", "a Hitron cable gateway (often Xfinity OEM)", 6),
        (false, "actiontec", "ap", "an Actiontec FiOS or Frontier gateway", 6),
        (false, "buffalo", "ap", "a Buffalo AirStation or router", 6),
        (false, "grandstream", "ap", "a Grandstream GWN access point", 6),
        (false, "edgecore", "ap", "an Edgecore access point", 7),
        (false, "watchguard ap", "ap", "a WatchGuard firewall or access point", 7),
        (false, "mojo", "ap", "a Mojo Networks / Arista Cognitive Wi-Fi access point", 7),
        (false, "winegard", "hotspot", "a Winegard RV or marine Wi-Fi radio", 6),
        (false, "inseego", "ap", "an Inseego 5G or MiFi hotspot", 6),
        (false, "franklin", "ap", "a Franklin Technology 5G home-internet gateway (RG3100 class)", 6),
        (false, "synology", "ap", "a Synology NAS or router access point", 6),
        (false, "aruba", "ap", "an HPE Aruba Instant or Instant On access point", 7),
        (false, "ruckus", "ap", "a RUCKUS access point", 7),
        (false, "fortinet", "ap", "a Fortinet FortiAP or FortiWiFi", 7),
        (false, "mikrotik", "ap", "a MikroTik router or access point", 6),
        (false, "engenius", "ap", "an EnGenius access point", 6),
        (false, "zyxel", "ap", "a Zyxel gateway or access point", 6),
        (false, "peplink", "ap", "a Peplink or Pepwave router", 6),
        (false, "openwrt", "ap", "an OpenWrt router", 6),
        (false, "arris", "ap", "an Arris or SURFboard cable gateway", 6),
        (false, "unifi ap", "ap", "a Ubiquiti UniFi access point", 7),
        (false, "unifi protect", "camera", "a UniFi Protect Instant camera", 7),
        (false, "unifi", "ap", "a UniFi / Ubiquiti name", 5),
        (false, "ecobee", "thermostat", "an ecobee thermostat", 7),
        (false, "sensi", "thermostat", "a Sensi thermostat", 6),
        (false, "honeywell home", "thermostat", "a Honeywell Home or Lyric thermostat", 6),
        (true, "honeywell xenon", "health", "a Honeywell Xenon healthcare barcode scanner", 7),
        (false, "omron", "health", "an Omron blood-pressure cuff or scale", 7),
        (false, "withings", "health", "a Withings scale or blood-pressure monitor", 7),
        (false, "dexcom", "health", "a Dexcom glucose sensor", 7),
        (false, "nest thermostat", "thermostat", "a Nest thermostat or Nest Labs BLE sensor", 6),
        (false, "nest weave", "sensor", "a Nest Protect, camera, or other Weave BLE device", 7),
        (false, "haiku fan", "fan", "a Haiku or Mammoth ceiling fan", 7),
        (false, "haiku", "fan", "a Haiku or Mammoth ceiling fan", 7),
        (false, "tuya", "iot", "a Tuya BLE gadget (plug, light, camera, sensor)", 6),
        (false, "seos", "access", "an ASSA ABLOY lock, Yale lock, HID reader, or Seos credential", 7),
        (false, "assa abloy", "access", "an ASSA ABLOY lock, Yale lock, HID reader, or Seos credential", 7),
        (false, "august", "lock", "an August smart lock", 7),
        (false, "schlage", "lock", "a Schlage or Allegion lock", 7),
        (false, "nuki", "lock", "a Nuki lock or opener", 7),
        (false, "salto", "access", "a SALTO access reader or lock", 7),
        (false, "dormakaba", "access", "a dormakaba, Saflok, or Oracode lock", 7),
        (false, "lockly", "lock", "a Lockly smart lock", 6),
        (false, "kevo", "lock", "a Kwikset Kevo or Unikey lock", 7),
        (false, "master lock", "lock", "a Master Lock padlock", 7),
        (false, "igloohome", "lock", "an igloohome lock or keybox", 7),
        (false, "tedee", "lock", "a Tedee smart lock", 7),
        (false, "paxton", "access", "a Paxton reader or Net2 access point", 7),
        (false, "kwikset", "lock", "a Kwikset lock", 6),
        (false, "myq", "garage", "a Chamberlain myQ garage hub", 7),
        (false, "chevrolet hotspot", "hotspot", "a Chevrolet in-car Wi-Fi hotspot", 7),
        (false, "rivian", "vehicle", "a Rivian vehicle, phone key, or sensor", 7),
        (false, "ford", "vehicle", "a Ford or Lincoln vehicle or phone-as-key", 7),
        (false, "honda", "vehicle", "a Honda or Acura vehicle or phone-as-key", 7),
        (false, "hyundai", "vehicle", "a Hyundai or Genesis vehicle or phone-as-key", 7),
        (false, "toyota", "vehicle", "a Toyota or Lexus vehicle or phone-as-key", 7),
        (false, "nissan", "vehicle", "a Nissan or Infiniti vehicle or phone-as-key", 7),
        (false, "subaru", "vehicle", "a Subaru vehicle or phone-as-key", 7),
        (false, "bmw", "vehicle", "a BMW vehicle, phone-as-key, or factory hotspot", 7),
        (false, "volkswagen", "vehicle", "a Volkswagen vehicle or phone-as-key", 7),
        (false, "porsche", "vehicle", "a Porsche vehicle or phone-as-key", 7),
        (false, "jaguar land rover", "vehicle", "a Jaguar, Land Rover, or Range Rover", 7),
        (false, "byd", "vehicle", "a BYD vehicle or phone-as-key", 7),
        (false, "govee", "light", "a Govee light or sensor", 6),
        (false, "hp", "printer", "an HP printer", 6),
        (false, "epson", "printer", "an Epson EcoTank or WorkForce printer", 6),
        (false, "lg webos tv", "tv", "an LG webOS TV", 7),
        (false, "roku", "tv", "a Roku streaming stick or Roku TV (often a hidden Wi-Fi Direct remote AP)", 7),
        (false, "samsung appliance", "iot", "a Samsung fridge, range, oven, or cooktop (setup AP)", 6),
        (false, "ecowater", "iot", "an EcoWater water softener (setup AP)", 6),
        (false, "nespresso", "iot", "a Nespresso coffee machine", 7),
        (false, "radiacode", "sensor", "a RadiaCode radiation detector", 7),
        (false, "shokz", "audio-personal", "Shokz OpenRun or OpenFit headphones", 7),
        (false, "mercedes mbux", "hotspot", "a Mercedes MBUX in-car hotspot", 7),
        (false, "motive", "hotspot", "a Motive / KeepTruckin fleet ELD hotspot", 6),
        (false, "peoplenet", "hotspot", "a PeopleNet fleet ELD hotspot", 6),
        (false, "uconnect", "hotspot", "a Uconnect in-car hotspot", 6),
        (false, "carplay", "hotspot", "a CarPlay in-car hotspot", 6),
        (false, "cradlepoint", "hotspot", "a Cradlepoint vehicle router (often public-safety / fleet)", 7),
        (false, "airlink", "hotspot", "a Sierra Wireless AirLink vehicle gateway", 7),
        (false, "compex", "hotspot", "a Compex access point (sometimes public-safety / fleet)", 6),
        (false, "novatel wireless", "hotspot", "a Novatel Wireless / Inseego vehicle radio", 6),
        (false, "utility inc", "hotspot", "a Utility, Inc vehicle or public-safety radio", 6),
        (true, "gl.inet", "ap", "a GL.iNet travel router", 6),
        (false, "glinet", "ap", "a GL.iNet travel router", 6),
        (true, "smarttag", "tag", "a Samsung SmartTag", 8),
        (true, "tile", "tag", "a Tile tracker", 8),
        (false, "ibeacon", "beacon", "an iBeacon", 7),
        (true, "target atrius", "beacon", "a Target Atrius basket tag", 8),
        (false, "minew", "beacon", "a Minew BLE beacon or sensor", 7),
        (false, "estimote", "beacon", "an Estimote beacon", 7),
        (false, "kontakt.io", "beacon", "a Kontakt.io beacon", 7),
        (false, "kontakt", "beacon", "a Kontakt.io beacon", 7),
        (true, "bluetoad", "roadside", "an Iteris BlueTOAD / Vantage Velocity roadside Bluetooth travel-time reader", 7),
        (true, "bliptrack", "roadside", "a BLIP Systems BlipTrack roadside travel-time sensor", 7),
        (true, "raven", "acoustic", "a Flock Raven or ShotSpotter acoustic gunshot sensor", 8),
        (true, "shotspotter", "acoustic", "a Flock Raven or ShotSpotter acoustic gunshot sensor", 8),
        (true, "soundthinking", "acoustic", "a Flock Raven or ShotSpotter acoustic gunshot sensor", 8),
        (true, "digital ally", "camera", "a Digital Ally body-worn or in-car camera", 8),
        (true, "reveal media", "camera", "a Reveal Media body-worn camera", 8),
        (true, "bodyworn", "camera", "a Reveal Media body-worn camera", 8),
        (false, "wolfcom", "camera", "a Wolfcom body-worn or in-car camera", 8),
        (true, "i-pro", "camera", "a Panasonic i-PRO camera or Arbitrator in-car system", 8),
        (true, "arbitrator", "camera", "a Panasonic i-PRO camera or Arbitrator in-car system", 8),
        (true, "limitless", "wearable", "a Limitless Pendant conversation recorder", 8),
        (false, "bee pendant", "wearable", "a Bee Pioneer wearable recorder", 8),
        (true, "bee pioneer", "wearable", "a Bee Pioneer wearable recorder", 8),
        (false, "omi", "wearable", "an Omi pendant or OpenGlass camera glasses", 8),
        (true, "openglass", "wearable", "an Omi pendant or OpenGlass camera glasses", 8),
        (true, "friend pendant", "wearable", "a Friend Pendant necklace", 8),
        (true, "brilliant frame", "glasses", "Brilliant Labs Frame AR glasses", 8),
        (false, "even g1", "glasses", "Even Realities G1 glasses", 8),
        (true, "hayden", "camera", "a Hayden AI bus- or vehicle-mounted camera", 8),
        (true, "miovision", "camera", "a Miovision intersection traffic camera", 8),
        (false, "tattile", "camera", "a Tattile plate reader", 8),
        (true, "lvt", "camera", "an LVT / LiveView solar surveillance trailer", 8),
        (true, "liveview", "camera", "an LVT / LiveView solar surveillance trailer", 8),
        (true, "hanwha", "camera", "a Hanwha Vision / Wisenet camera", 7),
        (true, "wisenet", "camera", "a Hanwha Vision / Wisenet camera", 7),
        (false, "uniview", "camera", "a Uniview / UNV camera", 7),
        (false, "rhombus", "camera", "a Rhombus cloud camera", 7),
        (false, "meshcore", "mesh", "a MeshCore LoRa companion radio", 7),
        (true, "gotenna", "mesh", "a goTenna Mesh or Pro radio", 7),
        (false, "sensecap", "mesh", "a SenseCAP LoRaWAN / Helium gateway", 7),
        (true, "wisgate", "mesh", "a RAK WisGate LoRaWAN gateway", 7),
        (false, "rak wisgate", "mesh", "a RAK WisGate LoRaWAN gateway", 7),
        (false, "ghostesp", "pentest", "a GhostESP ESP32 audit board", 7),
        (false, "bruce", "pentest", "a Bruce ESP32 pentest board", 7),
        (false, "liteon camera radio", "module", "a camera-module radio (LiteOn or similar)", 3),
        (true, "chipolo", "tag", "a finder tag", 7),
        (true, "pebblebee", "tag", "a finder tag", 7),
        (true, "moto tag", "tag", "a finder tag", 7),
        (true, "airpods", "audio-personal", "AirPods", 8),
]
